module.exports =  {
    uTN8WP10HY: 'AC',
    XHUDIFEjQy: 'AL',
    kfOtyvDHh3: 'AP',
    kZjftVxsJ2: 'AM',
    alzUcJAbsL: 'BA',
    ThJDLoQlin: 'CE',
    U8jHH89IkZ: 'DF',
    LlLUQQW7em: 'ES',
    MOPNB3fPnM: 'GO',
    fwHJWgSphk: 'MA',
    '2v59GBInrd': 'MG',
    EgBxJSFJkf: 'MS',
    EPgf4v3eYo: 'MT',
    cSB7DrlxKW: 'PR',
    '6eSlyH3T4n': 'PB',
    d1ejs3xsWl: 'PA',
    fnVKeAvGLb: 'PE',
    gQiBOengLe: 'PI',
    ZEqcJDbUUk: 'RN',
    zWseWwWhhn: 'RS',
    SgfpOQHx9r: 'RJ',
    IeCnkqtfOf: 'RO',
    OpUETQp72a: 'RR',
    v64fT2DVSw: 'SC',
    VpSNd1zJrg: 'SE',
    AIzthCzqdx: 'SP',
    bsZ2atdJ6V: 'TO',

  }